---
title: "mrio_visualizations"
author: "Megan Zhang"
date: "2024-12-21"
output: html_document
---

```{r libraries}
library(ggplot2)  
library(reshape2)  
library(plotly)  
library(corrplot)
library(pheatmap)
```

```{r load matrices}
io_table <- read.csv("C:/Users/megan/mz_codes/broadband-mrio/eora_bb.csv", header = FALSE)

```

```{r 2}
sector_names <- io_table[2, -c(1, 2)]  # Sector names excluding first two columns
region_and_sector <- io_table[, 1:2]   # First two columns for region/sector labels
numeric_data <- as.matrix(io_table[-(1:3), -c(1, 2)])
```

```{r 3}
sectors_of_interest <- c("Post and Telecommunications","Electrical and Machinery","Construction","Transport","Finacial Intermediation and Business Activities")

total_monetary_value <- 0  
  
for (i in 1:nrow(numeric_data)) {  
  for (j in 1:ncol(numeric_data)) {  
   # Convert the current element to numeric and add it to the total  
   total_monetary_value <- total_monetary_value + as.numeric(numeric_data[i, j])  
  }  
}  
  
print(paste("Total monetary value: ", total_monetary_value))

```

```{r 4}
sector_outputs <- rep(0, length(sectors_of_interest))  
 
for (j in 1:ncol(numeric_data)) {  
  # Extract the current sector name  
  sector_name <- sector_names[j]  
   
 
  for (k in 1:length(sectors_of_interest)) {  
   if (grepl(sectors_of_interest[k], sector_name, ignore.case = TRUE)) {  
    for (i in 1:nrow(numeric_data)) {  

      numeric_value <- as.numeric(as.character(numeric_data[i, j]))  
       
 
      if (!is.na(numeric_value)) {  
       sector_outputs[k] <- sector_outputs[k] + numeric_value  
      } else {  

       warning(paste("Non-numeric value found at row", i, "column", j))  
      }  
    }  
   }  
  }  
}  
  
plot_df <- data.frame(  
  Sector = sectors_of_interest,  
  Total_Output = sector_outputs  
)  

ggplot(plot_df, aes(x = Sector, y = Total_Output)) +  
  geom_col() +   
  labs(  
   title = "Total Output by Sector of Interest",  
   subtitle = "Monetary Value (millions of USD)",  
   x = "",   
   y = "Total Output"  
  ) +  
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +   
  scale_y_continuous(labels = function(x) formatC(x, format = "d", big.mark = ",")) 
 

```